# Site settings
title: Swetank Modi's CV
description: swetankmodi's CV
favicon: /assets/img/avatar.JPG
baseurl: https://ddbullfrog.github.io/resumecard
url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Swetank Modi
  title: Software Developer
  address: Kolkata, India
  email: contact@socialhub.in
  link: http://swetankmodi.me
  weibo:
  github: swetankmodi
  linkedin: swetank-modi
  twitter: swetankmodi
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow: 6731983
  workHistory:
    - work1:
      company: Directi Internet Solutions
      location: Mumbai, India
      title: Software Development Intern
      started: 2018
      duration: (June 2018 - Present)
      description: Worked on queuing and auto execution of jobs in the backend with status logs so that there is no extra load on the server.
    - work2:
      company: GeeksForGeeks
      location: Delhi, India (Remote)
      title: Technical Scripter
      started: 2017
      duration: (December 2017 - Present)
      description: Written various articles on datastructures and algorithms and improved articles by re-writing codes in different languages.
    - work3:
      company: XRIG Pvt Ltd
      location: Kolkata, India
      title: Software Developer
      started: 2017
      duration: (July 2017 - September 2018)
      description: Built the startup website and a customised cloud based erp solution for automating the inventory.
    - work4:
      company: Exide Industries Ltd
      location: Kolkata, India
      title: Software Developer Trainee
      started: 2017
      duration: (June 2017 - July 2017)
      description: Developed an asset management system for the company.
    - work5:
      company: Kolkata Bloggers
      location: Kolkata, India
      title: Developer
      started: 2017
      duration: (May 2017 - June 2018)
      description: Worked on an automated blog search chatbot.
  educationHistory:
    - education1:
      organization: Heritage Institute of Technology
      location: Kolkata, India
      degree: Bachelor
      major: Computer Science Engineering
      started: 2015
      duration: (2015 - 2019)
      description: Currently in 7th Semester, with a C.G.P.A of (8.898/10.0000). Expected Graduation Date - June 2019.
  languages:
    - language1:
      name: Hindi
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Bengali
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: C++
      percentage: 100%
    - skill2:
      name: PHP
      percentage: 100%
    - skill3: 
      name: Python
      percentage: 90%
    - skill4:
      name: C
      percentage: 90%
    - skill5:
      name: SQL
      percentage: 90%
    - skill6:
      name: Java
      percentage: 80%
    - skill7:
      name: JavaScript
      percentage: 65%
